// Copyright 2022 Google LLC All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code was autogenerated. Do not edit directly.
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: agones.dev/agones/pkg/apis/autoscaling/v1/generated.proto

package v1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"
	v12 "k8s.io/api/admissionregistration/v1"
	v11 "k8s.io/apimachinery/pkg/apis/meta/v1"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"

	k8s_io_apimachinery_pkg_types "k8s.io/apimachinery/pkg/types"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *BufferPolicy) Reset()      { *m = BufferPolicy{} }
func (*BufferPolicy) ProtoMessage() {}
func (*BufferPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{0}
}
func (m *BufferPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BufferPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *BufferPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BufferPolicy.Merge(m, src)
}
func (m *BufferPolicy) XXX_Size() int {
	return m.Size()
}
func (m *BufferPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_BufferPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_BufferPolicy proto.InternalMessageInfo

func (m *CounterPolicy) Reset()      { *m = CounterPolicy{} }
func (*CounterPolicy) ProtoMessage() {}
func (*CounterPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{1}
}
func (m *CounterPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CounterPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *CounterPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterPolicy.Merge(m, src)
}
func (m *CounterPolicy) XXX_Size() int {
	return m.Size()
}
func (m *CounterPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_CounterPolicy proto.InternalMessageInfo

func (m *FixedIntervalSync) Reset()      { *m = FixedIntervalSync{} }
func (*FixedIntervalSync) ProtoMessage() {}
func (*FixedIntervalSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{2}
}
func (m *FixedIntervalSync) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FixedIntervalSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FixedIntervalSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FixedIntervalSync.Merge(m, src)
}
func (m *FixedIntervalSync) XXX_Size() int {
	return m.Size()
}
func (m *FixedIntervalSync) XXX_DiscardUnknown() {
	xxx_messageInfo_FixedIntervalSync.DiscardUnknown(m)
}

var xxx_messageInfo_FixedIntervalSync proto.InternalMessageInfo

func (m *FleetAutoscaleRequest) Reset()      { *m = FleetAutoscaleRequest{} }
func (*FleetAutoscaleRequest) ProtoMessage() {}
func (*FleetAutoscaleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{3}
}
func (m *FleetAutoscaleRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FleetAutoscaleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FleetAutoscaleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FleetAutoscaleRequest.Merge(m, src)
}
func (m *FleetAutoscaleRequest) XXX_Size() int {
	return m.Size()
}
func (m *FleetAutoscaleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FleetAutoscaleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FleetAutoscaleRequest proto.InternalMessageInfo

func (m *FleetAutoscaleResponse) Reset()      { *m = FleetAutoscaleResponse{} }
func (*FleetAutoscaleResponse) ProtoMessage() {}
func (*FleetAutoscaleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{4}
}
func (m *FleetAutoscaleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FleetAutoscaleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FleetAutoscaleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FleetAutoscaleResponse.Merge(m, src)
}
func (m *FleetAutoscaleResponse) XXX_Size() int {
	return m.Size()
}
func (m *FleetAutoscaleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FleetAutoscaleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FleetAutoscaleResponse proto.InternalMessageInfo

func (m *FleetAutoscaleReview) Reset()      { *m = FleetAutoscaleReview{} }
func (*FleetAutoscaleReview) ProtoMessage() {}
func (*FleetAutoscaleReview) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{5}
}
func (m *FleetAutoscaleReview) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FleetAutoscaleReview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FleetAutoscaleReview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FleetAutoscaleReview.Merge(m, src)
}
func (m *FleetAutoscaleReview) XXX_Size() int {
	return m.Size()
}
func (m *FleetAutoscaleReview) XXX_DiscardUnknown() {
	xxx_messageInfo_FleetAutoscaleReview.DiscardUnknown(m)
}

var xxx_messageInfo_FleetAutoscaleReview proto.InternalMessageInfo

func (m *FleetAutoscaler) Reset()      { *m = FleetAutoscaler{} }
func (*FleetAutoscaler) ProtoMessage() {}
func (*FleetAutoscaler) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{6}
}
func (m *FleetAutoscaler) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FleetAutoscaler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FleetAutoscaler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FleetAutoscaler.Merge(m, src)
}
func (m *FleetAutoscaler) XXX_Size() int {
	return m.Size()
}
func (m *FleetAutoscaler) XXX_DiscardUnknown() {
	xxx_messageInfo_FleetAutoscaler.DiscardUnknown(m)
}

var xxx_messageInfo_FleetAutoscaler proto.InternalMessageInfo

func (m *FleetAutoscalerList) Reset()      { *m = FleetAutoscalerList{} }
func (*FleetAutoscalerList) ProtoMessage() {}
func (*FleetAutoscalerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{7}
}
func (m *FleetAutoscalerList) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FleetAutoscalerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FleetAutoscalerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FleetAutoscalerList.Merge(m, src)
}
func (m *FleetAutoscalerList) XXX_Size() int {
	return m.Size()
}
func (m *FleetAutoscalerList) XXX_DiscardUnknown() {
	xxx_messageInfo_FleetAutoscalerList.DiscardUnknown(m)
}

var xxx_messageInfo_FleetAutoscalerList proto.InternalMessageInfo

func (m *FleetAutoscalerPolicy) Reset()      { *m = FleetAutoscalerPolicy{} }
func (*FleetAutoscalerPolicy) ProtoMessage() {}
func (*FleetAutoscalerPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{8}
}
func (m *FleetAutoscalerPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FleetAutoscalerPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FleetAutoscalerPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FleetAutoscalerPolicy.Merge(m, src)
}
func (m *FleetAutoscalerPolicy) XXX_Size() int {
	return m.Size()
}
func (m *FleetAutoscalerPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_FleetAutoscalerPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_FleetAutoscalerPolicy proto.InternalMessageInfo

func (m *FleetAutoscalerSpec) Reset()      { *m = FleetAutoscalerSpec{} }
func (*FleetAutoscalerSpec) ProtoMessage() {}
func (*FleetAutoscalerSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{9}
}
func (m *FleetAutoscalerSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FleetAutoscalerSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FleetAutoscalerSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FleetAutoscalerSpec.Merge(m, src)
}
func (m *FleetAutoscalerSpec) XXX_Size() int {
	return m.Size()
}
func (m *FleetAutoscalerSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_FleetAutoscalerSpec.DiscardUnknown(m)
}

var xxx_messageInfo_FleetAutoscalerSpec proto.InternalMessageInfo

func (m *FleetAutoscalerStatus) Reset()      { *m = FleetAutoscalerStatus{} }
func (*FleetAutoscalerStatus) ProtoMessage() {}
func (*FleetAutoscalerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{10}
}
func (m *FleetAutoscalerStatus) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FleetAutoscalerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FleetAutoscalerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FleetAutoscalerStatus.Merge(m, src)
}
func (m *FleetAutoscalerStatus) XXX_Size() int {
	return m.Size()
}
func (m *FleetAutoscalerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_FleetAutoscalerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_FleetAutoscalerStatus proto.InternalMessageInfo

func (m *FleetAutoscalerSync) Reset()      { *m = FleetAutoscalerSync{} }
func (*FleetAutoscalerSync) ProtoMessage() {}
func (*FleetAutoscalerSync) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{11}
}
func (m *FleetAutoscalerSync) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FleetAutoscalerSync) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *FleetAutoscalerSync) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FleetAutoscalerSync.Merge(m, src)
}
func (m *FleetAutoscalerSync) XXX_Size() int {
	return m.Size()
}
func (m *FleetAutoscalerSync) XXX_DiscardUnknown() {
	xxx_messageInfo_FleetAutoscalerSync.DiscardUnknown(m)
}

var xxx_messageInfo_FleetAutoscalerSync proto.InternalMessageInfo

func (m *ListPolicy) Reset()      { *m = ListPolicy{} }
func (*ListPolicy) ProtoMessage() {}
func (*ListPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{12}
}
func (m *ListPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *ListPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPolicy.Merge(m, src)
}
func (m *ListPolicy) XXX_Size() int {
	return m.Size()
}
func (m *ListPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_ListPolicy proto.InternalMessageInfo

func (m *WebhookPolicy) Reset()      { *m = WebhookPolicy{} }
func (*WebhookPolicy) ProtoMessage() {}
func (*WebhookPolicy) Descriptor() ([]byte, []int) {
	return fileDescriptor_b73e7dcfde160fe7, []int{13}
}
func (m *WebhookPolicy) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WebhookPolicy) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *WebhookPolicy) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WebhookPolicy.Merge(m, src)
}
func (m *WebhookPolicy) XXX_Size() int {
	return m.Size()
}
func (m *WebhookPolicy) XXX_DiscardUnknown() {
	xxx_messageInfo_WebhookPolicy.DiscardUnknown(m)
}

var xxx_messageInfo_WebhookPolicy proto.InternalMessageInfo

func init() {
	proto.RegisterType((*BufferPolicy)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.BufferPolicy")
	proto.RegisterType((*CounterPolicy)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.CounterPolicy")
	proto.RegisterType((*FixedIntervalSync)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.FixedIntervalSync")
	proto.RegisterType((*FleetAutoscaleRequest)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.FleetAutoscaleRequest")
	proto.RegisterType((*FleetAutoscaleResponse)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.FleetAutoscaleResponse")
	proto.RegisterType((*FleetAutoscaleReview)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.FleetAutoscaleReview")
	proto.RegisterType((*FleetAutoscaler)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.FleetAutoscaler")
	proto.RegisterType((*FleetAutoscalerList)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.FleetAutoscalerList")
	proto.RegisterType((*FleetAutoscalerPolicy)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.FleetAutoscalerPolicy")
	proto.RegisterType((*FleetAutoscalerSpec)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.FleetAutoscalerSpec")
	proto.RegisterType((*FleetAutoscalerStatus)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.FleetAutoscalerStatus")
	proto.RegisterType((*FleetAutoscalerSync)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.FleetAutoscalerSync")
	proto.RegisterType((*ListPolicy)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.ListPolicy")
	proto.RegisterType((*WebhookPolicy)(nil), "agones.dev.agones.pkg.apis.autoscaling.v1.WebhookPolicy")
}

func init() {
	proto.RegisterFile("agones.dev/agones/pkg/apis/autoscaling/v1/generated.proto", fileDescriptor_b73e7dcfde160fe7)
}

var fileDescriptor_b73e7dcfde160fe7 = []byte{
	// 1295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x57, 0xcd, 0x6f, 0x1b, 0x45,
	0x14, 0xcf, 0xc6, 0x4e, 0xe3, 0x8c, 0xe3, 0x86, 0x4e, 0xe9, 0xa7, 0x84, 0x53, 0xcc, 0x81, 0x04,
	0xc1, 0x6e, 0x93, 0xb6, 0x50, 0xbe, 0x2a, 0xb2, 0xa9, 0x2a, 0x45, 0xa4, 0x2d, 0x1a, 0xa7, 0x42,
	0x40, 0xa4, 0x76, 0xbc, 0x3b, 0x76, 0x06, 0x7b, 0x3f, 0xd8, 0x99, 0x75, 0x6b, 0x4e, 0x88, 0x1b,
	0x17, 0xc4, 0x7f, 0x82, 0xc4, 0x3f, 0xc0, 0x35, 0x42, 0x42, 0xea, 0x81, 0x43, 0x4f, 0x11, 0x31,
	0x57, 0xfe, 0x01, 0x7a, 0x01, 0xcd, 0xc7, 0x7e, 0x78, 0xed, 0xb4, 0x49, 0x03, 0x27, 0x4e, 0xde,
	0x99, 0xf7, 0x7e, 0xbf, 0x37, 0xef, 0xcd, 0x7b, 0x6f, 0x9e, 0xc1, 0xbb, 0xb8, 0x13, 0xf8, 0x84,
	0x99, 0x2e, 0xe9, 0x5b, 0xea, 0xd3, 0x0a, 0xbb, 0x1d, 0x0b, 0x87, 0x94, 0x59, 0x38, 0xe6, 0x01,
	0x73, 0x70, 0x8f, 0xfa, 0x1d, 0xab, 0xbf, 0x62, 0x75, 0x88, 0x4f, 0x22, 0xcc, 0x89, 0x6b, 0x86,
	0x51, 0xc0, 0x03, 0xb8, 0x9c, 0x41, 0x4d, 0xfd, 0x19, 0x76, 0x3b, 0xa6, 0x80, 0x9a, 0x39, 0xa8,
	0xd9, 0x5f, 0xb9, 0x78, 0xf5, 0x59, 0x56, 0xd4, 0x7a, 0xdc, 0xc0, 0xc5, 0xb7, 0x3a, 0x94, 0xef,
	0xc4, 0x2d, 0xd3, 0x09, 0x3c, 0xab, 0x13, 0x74, 0x02, 0x4b, 0x6e, 0xb7, 0xe2, 0xb6, 0x5c, 0xc9,
	0x85, 0xfc, 0xd2, 0xea, 0x57, 0xba, 0xd7, 0x99, 0x49, 0x03, 0xc1, 0x6a, 0x61, 0xd7, 0xa3, 0x8c,
	0xd1, 0xc0, 0x8f, 0x48, 0x87, 0x32, 0x1e, 0x61, 0x4e, 0x03, 0x7f, 0x92, 0x8d, 0xab, 0x19, 0xc8,
	0xc3, 0xce, 0x0e, 0xf5, 0x49, 0x34, 0xc8, 0xce, 0xe6, 0x11, 0x8e, 0x27, 0xa1, 0xac, 0x83, 0x50,
	0x51, 0xec, 0x73, 0xea, 0x91, 0x31, 0xc0, 0xdb, 0xcf, 0x03, 0x30, 0x67, 0x87, 0x78, 0x78, 0x0c,
	0x77, 0xe5, 0x20, 0x5c, 0xcc, 0x69, 0xcf, 0xa2, 0x3e, 0x67, 0x3c, 0x2a, 0x82, 0x1a, 0x43, 0x03,
	0xcc, 0xdb, 0x71, 0xbb, 0x4d, 0xa2, 0x4f, 0x82, 0x1e, 0x75, 0x06, 0xf0, 0x1a, 0xa8, 0x7a, 0xf8,
	0x11, 0x22, 0x61, 0x8f, 0x3a, 0x98, 0x9d, 0x37, 0x2e, 0x19, 0x4b, 0x33, 0xf6, 0xe9, 0xdd, 0xbd,
	0xc5, 0xa9, 0xe1, 0xde, 0x62, 0xf5, 0x76, 0x26, 0x42, 0x79, 0x3d, 0x09, 0xa3, 0x7e, 0x0a, 0x9b,
	0x2e, 0xc0, 0x32, 0x11, 0xca, 0xeb, 0x41, 0x17, 0x80, 0x96, 0xb4, 0xde, 0xa4, 0x5f, 0x93, 0xf3,
	0xa5, 0x4b, 0xc6, 0x52, 0x75, 0xf5, 0xb2, 0xa9, 0x1c, 0x31, 0xf3, 0x8e, 0xc8, 0x74, 0x11, 0x8e,
	0x98, 0xca, 0x11, 0x73, 0xc3, 0xe7, 0x77, 0xa3, 0x26, 0x8f, 0xa8, 0xdf, 0xb1, 0xa1, 0xb6, 0x03,
	0xec, 0x94, 0x0b, 0xe5, 0x78, 0x1b, 0xdf, 0x4e, 0x83, 0xda, 0x7a, 0x10, 0xfb, 0x3c, 0xf5, 0xf2,
	0x15, 0x50, 0xea, 0x92, 0x81, 0xf4, 0x6e, 0xce, 0xae, 0x6a, 0x78, 0xe9, 0x63, 0x32, 0x40, 0x62,
	0x5f, 0x07, 0x61, 0x1d, 0x87, 0xd8, 0xa1, 0x7c, 0x20, 0xbd, 0x29, 0x8d, 0x04, 0x21, 0x11, 0xa1,
	0xbc, 0x9e, 0x0e, 0x42, 0x0a, 0x2b, 0x15, 0x60, 0x99, 0x08, 0xe5, 0xf5, 0x0a, 0x41, 0x28, 0xff,
	0x47, 0x41, 0xb8, 0x01, 0x4e, 0xdd, 0xa2, 0x8f, 0x88, 0xbb, 0x21, 0xc2, 0xd0, 0xc7, 0xbd, 0xe6,
	0xc0, 0x77, 0xe0, 0x32, 0x98, 0x65, 0xc4, 0x09, 0x7c, 0x37, 0xb9, 0xe9, 0x05, 0xcd, 0x32, 0xdb,
	0x54, 0xdb, 0x28, 0x91, 0x37, 0xbe, 0x9b, 0x06, 0x67, 0x6e, 0xf5, 0x08, 0xe1, 0x6b, 0xba, 0x5e,
	0x09, 0x22, 0x5f, 0xc5, 0x84, 0x71, 0x68, 0x83, 0x52, 0x4c, 0x5d, 0x1d, 0xcc, 0xcb, 0x49, 0x30,
	0xef, 0x6d, 0xdc, 0x7c, 0xba, 0xb7, 0xf8, 0xea, 0x41, 0x49, 0xc9, 0x07, 0x21, 0x61, 0xe6, 0xbd,
	0x8d, 0x9b, 0x48, 0x80, 0xe1, 0x25, 0x50, 0xf6, 0xb1, 0x47, 0x64, 0xa8, 0xe7, 0xec, 0x79, 0x4d,
	0x52, 0xbe, 0x83, 0x3d, 0x82, 0xa4, 0x04, 0x5a, 0x60, 0x4e, 0xfc, 0xb2, 0x10, 0x3b, 0x2a, 0x53,
	0xe6, 0xec, 0x53, 0x5a, 0x6d, 0xee, 0x4e, 0x22, 0x40, 0x99, 0x0e, 0xfc, 0x0c, 0x9c, 0x60, 0x1c,
	0xf3, 0x98, 0xe9, 0x90, 0xae, 0x98, 0xcf, 0x6a, 0x42, 0x6a, 0xdd, 0x5f, 0x31, 0xa5, 0x8f, 0x4d,
	0x09, 0xb4, 0x4f, 0x6a, 0x03, 0x27, 0xd4, 0x1a, 0x69, 0xc2, 0xc6, 0x8f, 0x06, 0x38, 0x5b, 0x8c,
	0x05, 0x0b, 0x03, 0x9f, 0x91, 0x7f, 0x25, 0x18, 0xaf, 0x81, 0x19, 0x49, 0x2a, 0xa3, 0x51, 0xb1,
	0x6b, 0x9a, 0x65, 0xa6, 0x29, 0x2d, 0x29, 0x19, 0x7c, 0x13, 0x54, 0xa2, 0xa4, 0xdc, 0x4a, 0xf2,
	0xee, 0x5e, 0xd2, 0x7a, 0x95, 0xb4, 0xd6, 0x52, 0x8d, 0xc6, 0x9f, 0x06, 0x78, 0xb9, 0x78, 0xe2,
	0x3e, 0x25, 0x0f, 0x61, 0x07, 0xcc, 0x46, 0xea, 0x1e, 0xe5, 0x99, 0xab, 0xab, 0x1f, 0x99, 0x87,
	0xee, 0xd5, 0xe6, 0xc4, 0x7c, 0xb0, 0xab, 0x22, 0x7f, 0xf4, 0x02, 0x25, 0xec, 0xb0, 0x2b, 0xce,
	0xab, 0x82, 0x24, 0xfd, 0xaa, 0xae, 0xae, 0x1d, 0xc3, 0x92, 0x22, 0xb2, 0xe7, 0x95, 0xbb, 0x6a,
	0x85, 0x52, 0x03, 0x8d, 0x9f, 0xa7, 0xc1, 0xc2, 0x28, 0x24, 0x82, 0x0f, 0x40, 0x45, 0xf4, 0x68,
	0x17, 0x73, 0xac, 0x5d, 0x3d, 0xb8, 0xc8, 0xe4, 0x11, 0x84, 0xb6, 0xb0, 0x7d, 0xb7, 0xf5, 0x25,
	0x71, 0xf8, 0x6d, 0xc2, 0x71, 0x56, 0x64, 0xd9, 0x1e, 0x4a, 0x59, 0xe1, 0x03, 0x50, 0x66, 0x21,
	0x71, 0xb4, 0x7b, 0x37, 0x5e, 0xd8, 0xbd, 0xa8, 0x19, 0x12, 0x27, 0x2b, 0x02, 0xb1, 0x42, 0x92,
	0x19, 0xee, 0xa4, 0x39, 0x5d, 0x3a, 0xe6, 0x65, 0x45, 0xcf, 0x49, 0xf1, 0xdf, 0x0c, 0x70, 0xba,
	0x80, 0xd8, 0xa4, 0x8c, 0xc3, 0xed, 0xb1, 0x28, 0x9a, 0x87, 0x8b, 0xa2, 0x40, 0xcb, 0x18, 0xa6,
	0x69, 0x9a, 0xec, 0xe4, 0x22, 0x78, 0x1f, 0xcc, 0x50, 0x4e, 0x3c, 0xf1, 0x80, 0x94, 0x96, 0xaa,
	0xab, 0xef, 0xbd, 0xb8, 0x7b, 0x59, 0xd5, 0x6c, 0x08, 0x42, 0xa4, 0x78, 0x1b, 0xbf, 0x94, 0x8a,
	0x5d, 0x2c, 0x79, 0x12, 0x3e, 0x04, 0x65, 0x51, 0x86, 0xba, 0x72, 0x97, 0x93, 0xe0, 0x6f, 0x0d,
	0x42, 0xf2, 0x74, 0x6f, 0xf1, 0xc2, 0x44, 0x90, 0x10, 0x22, 0x09, 0x83, 0x5f, 0x80, 0x13, 0xaa,
	0xd9, 0xea, 0xdb, 0x7f, 0xe7, 0x08, 0x47, 0xcf, 0x3f, 0xc0, 0x36, 0x10, 0x97, 0xa1, 0x76, 0x90,
	0xa6, 0x84, 0xf7, 0xc1, 0xec, 0x43, 0xd2, 0xda, 0x09, 0x82, 0xae, 0xbe, 0xf7, 0xeb, 0x47, 0x60,
	0xff, 0x54, 0x21, 0x35, 0xbd, 0x2c, 0x4e, 0xbd, 0x85, 0x12, 0x56, 0x61, 0xc0, 0x51, 0x0f, 0xa4,
	0x6e, 0x96, 0x47, 0x31, 0x30, 0xf2, 0xb4, 0x2a, 0x03, 0x7a, 0x0b, 0x25, 0xac, 0xb0, 0x09, 0xca,
	0x3d, 0xca, 0xf8, 0xf9, 0x19, 0xc9, 0x7e, 0xed, 0x08, 0xec, 0x22, 0x4b, 0x34, 0x75, 0x45, 0x5c,
	0x88, 0x58, 0x23, 0x49, 0xd6, 0xf8, 0x7e, 0x7a, 0x2c, 0x47, 0x45, 0xad, 0x88, 0xa7, 0xa2, 0x2d,
	0xb6, 0xc5, 0xb3, 0xa0, 0xef, 0x33, 0x7d, 0x2a, 0x6e, 0x25, 0x02, 0x94, 0xe9, 0x88, 0xb2, 0x0a,
	0xa5, 0x09, 0x7d, 0x79, 0xc7, 0x28, 0x2b, 0x7d, 0xd4, 0xb4, 0xac, 0xd4, 0x1a, 0x69, 0x7e, 0xb8,
	0x0d, 0xca, 0x6c, 0xe0, 0x3b, 0xfa, 0x1a, 0x8f, 0xd3, 0x22, 0x06, 0xbe, 0xa3, 0x02, 0x22, 0xbe,
	0x90, 0x64, 0x6d, 0xfc, 0x35, 0xf6, 0x46, 0xeb, 0x32, 0x87, 0x6b, 0x60, 0xc1, 0x89, 0xa3, 0x88,
	0xf8, 0xbc, 0x30, 0xda, 0x9d, 0xd3, 0x07, 0x5d, 0x58, 0x1f, 0x15, 0xa3, 0xa2, 0xbe, 0xa0, 0x70,
	0x09, 0xa3, 0x11, 0x71, 0x0b, 0x63, 0x5e, 0x4a, 0x71, 0x73, 0x54, 0x8c, 0x8a, 0xfa, 0xd0, 0x01,
	0xb5, 0x1e, 0x66, 0x5c, 0xbe, 0x63, 0x5b, 0xd4, 0x4b, 0x26, 0xbe, 0x37, 0x0e, 0xd7, 0x41, 0x04,
	0xc2, 0x3e, 0x35, 0xdc, 0x5b, 0xac, 0x6d, 0xe6, 0x49, 0xd0, 0x28, 0xa7, 0x98, 0xc2, 0x70, 0xab,
	0x47, 0xb6, 0x02, 0xb9, 0x25, 0xf3, 0xb9, 0x92, 0x4d, 0x61, 0x6b, 0x99, 0x08, 0xe5, 0xf5, 0xe0,
	0x0d, 0x70, 0x52, 0x47, 0x7b, 0x93, 0x7a, 0x94, 0x13, 0x57, 0xe6, 0x6a, 0xc5, 0x3e, 0xab, 0x91,
	0x27, 0x9b, 0x23, 0x52, 0x54, 0xd0, 0x6e, 0xfc, 0x3a, 0xde, 0x30, 0xe5, 0x88, 0xf5, 0xfe, 0x48,
	0x5f, 0x79, 0xbd, 0xd0, 0x57, 0xce, 0x4d, 0x80, 0xe4, 0xba, 0xca, 0x00, 0xd4, 0xda, 0xf9, 0xa1,
	0x4d, 0xe7, 0xe7, 0x07, 0x47, 0xc9, 0x9b, 0xe2, 0xd0, 0x67, 0x9f, 0xd1, 0x67, 0xa8, 0x8d, 0x88,
	0xd0, 0xa8, 0xa5, 0xc6, 0xdf, 0x06, 0x00, 0x59, 0xed, 0xfd, 0x1f, 0x27, 0xe6, 0x9f, 0x0c, 0x50,
	0x1b, 0x69, 0x9e, 0xf0, 0x02, 0x28, 0xc5, 0x51, 0x4f, 0x4f, 0x9f, 0xb3, 0x72, 0xb0, 0x43, 0x9b,
	0x48, 0xec, 0xc1, 0x6d, 0x31, 0x49, 0x47, 0x7d, 0xea, 0x10, 0xfd, 0x2c, 0x5e, 0xcb, 0x9d, 0xc7,
	0x9c, 0xf8, 0x1f, 0x53, 0xdc, 0x4e, 0x53, 0x61, 0x10, 0x69, 0x93, 0x88, 0xf8, 0x0e, 0x51, 0xed,
	0x33, 0xd9, 0x4d, 0x28, 0xe1, 0x12, 0xa8, 0x38, 0xd8, 0x8e, 0x7d, 0x57, 0x0f, 0x85, 0xf3, 0x6a,
	0xf2, 0x59, 0x5f, 0x53, 0x7b, 0x28, 0x95, 0xda, 0x77, 0x77, 0xf7, 0xeb, 0x53, 0x8f, 0xf7, 0xeb,
	0x53, 0x4f, 0xf6, 0xeb, 0x53, 0xdf, 0x0c, 0xeb, 0xc6, 0xee, 0xb0, 0x6e, 0x3c, 0x1e, 0xd6, 0x8d,
	0x27, 0xc3, 0xba, 0xf1, 0xfb, 0xb0, 0x6e, 0xfc, 0xf0, 0x47, 0x7d, 0xea, 0xf3, 0xe5, 0x43, 0xff,
	0x95, 0xff, 0x27, 0x00, 0x00, 0xff, 0xff, 0xd0, 0xf0, 0xa1, 0x09, 0xf6, 0x0f, 0x00, 0x00,
}

func (m *BufferPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BufferPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BufferPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BufferSize.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	i = encodeVarintGenerated(dAtA, i, uint64(m.MinReplicas))
	i--
	dAtA[i] = 0x10
	i = encodeVarintGenerated(dAtA, i, uint64(m.MaxReplicas))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *CounterPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CounterPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CounterPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BufferSize.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	i = encodeVarintGenerated(dAtA, i, uint64(m.MinCapacity))
	i--
	dAtA[i] = 0x18
	i = encodeVarintGenerated(dAtA, i, uint64(m.MaxCapacity))
	i--
	dAtA[i] = 0x10
	i -= len(m.Key)
	copy(dAtA[i:], m.Key)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Key)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FixedIntervalSync) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FixedIntervalSync) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FixedIntervalSync) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintGenerated(dAtA, i, uint64(m.Seconds))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *FleetAutoscaleRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FleetAutoscaleRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FleetAutoscaleRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	i -= len(m.Namespace)
	copy(dAtA[i:], m.Namespace)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Namespace)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Name)
	copy(dAtA[i:], m.Name)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Name)))
	i--
	dAtA[i] = 0x12
	i -= len(m.UID)
	copy(dAtA[i:], m.UID)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.UID)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FleetAutoscaleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FleetAutoscaleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FleetAutoscaleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i = encodeVarintGenerated(dAtA, i, uint64(m.Replicas))
	i--
	dAtA[i] = 0x18
	i--
	if m.Scale {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x10
	i -= len(m.UID)
	copy(dAtA[i:], m.UID)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.UID)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FleetAutoscaleReview) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FleetAutoscaleReview) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FleetAutoscaleReview) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Response != nil {
		{
			size, err := m.Response.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.Request != nil {
		{
			size, err := m.Request.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FleetAutoscaler) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FleetAutoscaler) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FleetAutoscaler) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Spec.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FleetAutoscalerList) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FleetAutoscalerList) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FleetAutoscalerList) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Items) > 0 {
		for iNdEx := len(m.Items) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Items[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ListMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FleetAutoscalerPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FleetAutoscalerPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FleetAutoscalerPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.List != nil {
		{
			size, err := m.List.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.Counter != nil {
		{
			size, err := m.Counter.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Webhook != nil {
		{
			size, err := m.Webhook.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Buffer != nil {
		{
			size, err := m.Buffer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	i -= len(m.Type)
	copy(dAtA[i:], m.Type)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Type)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FleetAutoscalerSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FleetAutoscalerSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FleetAutoscalerSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Sync != nil {
		{
			size, err := m.Sync.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	{
		size, err := m.Policy.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	i -= len(m.FleetName)
	copy(dAtA[i:], m.FleetName)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.FleetName)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *FleetAutoscalerStatus) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FleetAutoscalerStatus) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FleetAutoscalerStatus) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i--
	if m.ScalingLimited {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x28
	i--
	if m.AbleToScale {
		dAtA[i] = 1
	} else {
		dAtA[i] = 0
	}
	i--
	dAtA[i] = 0x20
	if m.LastScaleTime != nil {
		{
			size, err := m.LastScaleTime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	i = encodeVarintGenerated(dAtA, i, uint64(m.DesiredReplicas))
	i--
	dAtA[i] = 0x10
	i = encodeVarintGenerated(dAtA, i, uint64(m.CurrentReplicas))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}

func (m *FleetAutoscalerSync) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FleetAutoscalerSync) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FleetAutoscalerSync) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.FixedInterval.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	i -= len(m.Type)
	copy(dAtA[i:], m.Type)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Type)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ListPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ListPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BufferSize.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	i = encodeVarintGenerated(dAtA, i, uint64(m.MinCapacity))
	i--
	dAtA[i] = 0x18
	i = encodeVarintGenerated(dAtA, i, uint64(m.MaxCapacity))
	i--
	dAtA[i] = 0x10
	i -= len(m.Key)
	copy(dAtA[i:], m.Key)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Key)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *WebhookPolicy) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WebhookPolicy) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WebhookPolicy) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.URL != nil {
		i -= len(*m.URL)
		copy(dAtA[i:], *m.URL)
		i = encodeVarintGenerated(dAtA, i, uint64(len(*m.URL)))
		i--
		dAtA[i] = 0x1a
	}
	if m.CABundle != nil {
		i -= len(m.CABundle)
		copy(dAtA[i:], m.CABundle)
		i = encodeVarintGenerated(dAtA, i, uint64(len(m.CABundle)))
		i--
		dAtA[i] = 0x12
	}
	if m.Service != nil {
		{
			size, err := m.Service.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenerated(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BufferPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.MaxReplicas))
	n += 1 + sovGenerated(uint64(m.MinReplicas))
	l = m.BufferSize.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *CounterPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	n += 1 + l + sovGenerated(uint64(l))
	n += 1 + sovGenerated(uint64(m.MaxCapacity))
	n += 1 + sovGenerated(uint64(m.MinCapacity))
	l = m.BufferSize.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *FixedIntervalSync) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.Seconds))
	return n
}

func (m *FleetAutoscaleRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UID)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Name)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Namespace)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *FleetAutoscaleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UID)
	n += 1 + l + sovGenerated(uint64(l))
	n += 2
	n += 1 + sovGenerated(uint64(m.Replicas))
	return n
}

func (m *FleetAutoscaleReview) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Request != nil {
		l = m.Request.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Response != nil {
		l = m.Response.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *FleetAutoscaler) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Spec.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Status.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *FleetAutoscalerList) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ListMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.Items) > 0 {
		for _, e := range m.Items {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func (m *FleetAutoscalerPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	n += 1 + l + sovGenerated(uint64(l))
	if m.Buffer != nil {
		l = m.Buffer.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Webhook != nil {
		l = m.Webhook.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.Counter != nil {
		l = m.Counter.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.List != nil {
		l = m.List.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *FleetAutoscalerSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.FleetName)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.Policy.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if m.Sync != nil {
		l = m.Sync.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func (m *FleetAutoscalerStatus) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovGenerated(uint64(m.CurrentReplicas))
	n += 1 + sovGenerated(uint64(m.DesiredReplicas))
	if m.LastScaleTime != nil {
		l = m.LastScaleTime.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	n += 2
	n += 2
	return n
}

func (m *FleetAutoscalerSync) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Type)
	n += 1 + l + sovGenerated(uint64(l))
	l = m.FixedInterval.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *ListPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	n += 1 + l + sovGenerated(uint64(l))
	n += 1 + sovGenerated(uint64(m.MaxCapacity))
	n += 1 + sovGenerated(uint64(m.MinCapacity))
	l = m.BufferSize.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *WebhookPolicy) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Service != nil {
		l = m.Service.Size()
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.CABundle != nil {
		l = len(m.CABundle)
		n += 1 + l + sovGenerated(uint64(l))
	}
	if m.URL != nil {
		l = len(*m.URL)
		n += 1 + l + sovGenerated(uint64(l))
	}
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *BufferPolicy) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&BufferPolicy{`,
		`MaxReplicas:` + fmt.Sprintf("%v", this.MaxReplicas) + `,`,
		`MinReplicas:` + fmt.Sprintf("%v", this.MinReplicas) + `,`,
		`BufferSize:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.BufferSize), "IntOrString", "intstr.IntOrString", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *CounterPolicy) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&CounterPolicy{`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`MaxCapacity:` + fmt.Sprintf("%v", this.MaxCapacity) + `,`,
		`MinCapacity:` + fmt.Sprintf("%v", this.MinCapacity) + `,`,
		`BufferSize:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.BufferSize), "IntOrString", "intstr.IntOrString", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FixedIntervalSync) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FixedIntervalSync{`,
		`Seconds:` + fmt.Sprintf("%v", this.Seconds) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FleetAutoscaleRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FleetAutoscaleRequest{`,
		`UID:` + fmt.Sprintf("%v", this.UID) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`Status:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Status), "FleetStatus", "v1.FleetStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FleetAutoscaleResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FleetAutoscaleResponse{`,
		`UID:` + fmt.Sprintf("%v", this.UID) + `,`,
		`Scale:` + fmt.Sprintf("%v", this.Scale) + `,`,
		`Replicas:` + fmt.Sprintf("%v", this.Replicas) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FleetAutoscaleReview) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FleetAutoscaleReview{`,
		`Request:` + strings.Replace(this.Request.String(), "FleetAutoscaleRequest", "FleetAutoscaleRequest", 1) + `,`,
		`Response:` + strings.Replace(this.Response.String(), "FleetAutoscaleResponse", "FleetAutoscaleResponse", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FleetAutoscaler) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FleetAutoscaler{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v11.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`Spec:` + strings.Replace(strings.Replace(this.Spec.String(), "FleetAutoscalerSpec", "FleetAutoscalerSpec", 1), `&`, ``, 1) + `,`,
		`Status:` + strings.Replace(strings.Replace(this.Status.String(), "FleetAutoscalerStatus", "FleetAutoscalerStatus", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FleetAutoscalerList) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForItems := "[]FleetAutoscaler{"
	for _, f := range this.Items {
		repeatedStringForItems += strings.Replace(strings.Replace(f.String(), "FleetAutoscaler", "FleetAutoscaler", 1), `&`, ``, 1) + ","
	}
	repeatedStringForItems += "}"
	s := strings.Join([]string{`&FleetAutoscalerList{`,
		`ListMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ListMeta), "ListMeta", "v11.ListMeta", 1), `&`, ``, 1) + `,`,
		`Items:` + repeatedStringForItems + `,`,
		`}`,
	}, "")
	return s
}
func (this *FleetAutoscalerPolicy) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FleetAutoscalerPolicy{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`Buffer:` + strings.Replace(this.Buffer.String(), "BufferPolicy", "BufferPolicy", 1) + `,`,
		`Webhook:` + strings.Replace(this.Webhook.String(), "WebhookPolicy", "WebhookPolicy", 1) + `,`,
		`Counter:` + strings.Replace(this.Counter.String(), "CounterPolicy", "CounterPolicy", 1) + `,`,
		`List:` + strings.Replace(this.List.String(), "ListPolicy", "ListPolicy", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FleetAutoscalerSpec) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FleetAutoscalerSpec{`,
		`FleetName:` + fmt.Sprintf("%v", this.FleetName) + `,`,
		`Policy:` + strings.Replace(strings.Replace(this.Policy.String(), "FleetAutoscalerPolicy", "FleetAutoscalerPolicy", 1), `&`, ``, 1) + `,`,
		`Sync:` + strings.Replace(this.Sync.String(), "FleetAutoscalerSync", "FleetAutoscalerSync", 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FleetAutoscalerStatus) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FleetAutoscalerStatus{`,
		`CurrentReplicas:` + fmt.Sprintf("%v", this.CurrentReplicas) + `,`,
		`DesiredReplicas:` + fmt.Sprintf("%v", this.DesiredReplicas) + `,`,
		`LastScaleTime:` + strings.Replace(fmt.Sprintf("%v", this.LastScaleTime), "Time", "v11.Time", 1) + `,`,
		`AbleToScale:` + fmt.Sprintf("%v", this.AbleToScale) + `,`,
		`ScalingLimited:` + fmt.Sprintf("%v", this.ScalingLimited) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FleetAutoscalerSync) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FleetAutoscalerSync{`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`FixedInterval:` + strings.Replace(strings.Replace(this.FixedInterval.String(), "FixedIntervalSync", "FixedIntervalSync", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ListPolicy) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ListPolicy{`,
		`Key:` + fmt.Sprintf("%v", this.Key) + `,`,
		`MaxCapacity:` + fmt.Sprintf("%v", this.MaxCapacity) + `,`,
		`MinCapacity:` + fmt.Sprintf("%v", this.MinCapacity) + `,`,
		`BufferSize:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.BufferSize), "IntOrString", "intstr.IntOrString", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *WebhookPolicy) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&WebhookPolicy{`,
		`Service:` + strings.Replace(fmt.Sprintf("%v", this.Service), "ServiceReference", "v12.ServiceReference", 1) + `,`,
		`CABundle:` + valueToStringGenerated(this.CABundle) + `,`,
		`URL:` + valueToStringGenerated(this.URL) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *BufferPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BufferPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BufferPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxReplicas", wireType)
			}
			m.MaxReplicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxReplicas |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinReplicas", wireType)
			}
			m.MinReplicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinReplicas |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferSize", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BufferSize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CounterPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CounterPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CounterPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCapacity", wireType)
			}
			m.MaxCapacity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCapacity |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCapacity", wireType)
			}
			m.MinCapacity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCapacity |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferSize", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BufferSize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FixedIntervalSync) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FixedIntervalSync: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FixedIntervalSync: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Seconds", wireType)
			}
			m.Seconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Seconds |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FleetAutoscaleRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FleetAutoscaleRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FleetAutoscaleRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UID = k8s_io_apimachinery_pkg_types.UID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FleetAutoscaleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FleetAutoscaleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FleetAutoscaleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UID = k8s_io_apimachinery_pkg_types.UID(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Scale", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Scale = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Replicas", wireType)
			}
			m.Replicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Replicas |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FleetAutoscaleReview) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FleetAutoscaleReview: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FleetAutoscaleReview: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Request", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Request == nil {
				m.Request = &FleetAutoscaleRequest{}
			}
			if err := m.Request.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Response", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Response == nil {
				m.Response = &FleetAutoscaleResponse{}
			}
			if err := m.Response.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FleetAutoscaler) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FleetAutoscaler: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FleetAutoscaler: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Spec", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Spec.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FleetAutoscalerList) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FleetAutoscalerList: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FleetAutoscalerList: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ListMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ListMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Items", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Items = append(m.Items, FleetAutoscaler{})
			if err := m.Items[len(m.Items)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FleetAutoscalerPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FleetAutoscalerPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FleetAutoscalerPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = FleetAutoscalerPolicyType(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buffer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Buffer == nil {
				m.Buffer = &BufferPolicy{}
			}
			if err := m.Buffer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Webhook", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Webhook == nil {
				m.Webhook = &WebhookPolicy{}
			}
			if err := m.Webhook.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Counter == nil {
				m.Counter = &CounterPolicy{}
			}
			if err := m.Counter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field List", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.List == nil {
				m.List = &ListPolicy{}
			}
			if err := m.List.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FleetAutoscalerSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FleetAutoscalerSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FleetAutoscalerSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FleetName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FleetName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Policy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Policy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sync", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Sync == nil {
				m.Sync = &FleetAutoscalerSync{}
			}
			if err := m.Sync.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FleetAutoscalerStatus) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FleetAutoscalerStatus: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FleetAutoscalerStatus: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentReplicas", wireType)
			}
			m.CurrentReplicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentReplicas |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DesiredReplicas", wireType)
			}
			m.DesiredReplicas = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DesiredReplicas |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastScaleTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastScaleTime == nil {
				m.LastScaleTime = &v11.Time{}
			}
			if err := m.LastScaleTime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AbleToScale", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AbleToScale = bool(v != 0)
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScalingLimited", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ScalingLimited = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FleetAutoscalerSync) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FleetAutoscalerSync: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FleetAutoscalerSync: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Type = FleetAutoscalerSyncType(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FixedInterval", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FixedInterval.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxCapacity", wireType)
			}
			m.MaxCapacity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxCapacity |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinCapacity", wireType)
			}
			m.MinCapacity = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MinCapacity |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BufferSize", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BufferSize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *WebhookPolicy) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WebhookPolicy: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WebhookPolicy: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Service", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Service == nil {
				m.Service = &v12.ServiceReference{}
			}
			if err := m.Service.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CABundle", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CABundle = append(m.CABundle[:0], dAtA[iNdEx:postIndex]...)
			if m.CABundle == nil {
				m.CABundle = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field URL", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			s := string(dAtA[iNdEx:postIndex])
			m.URL = &s
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
